# Generated by Django 4.2 on 2023-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachment/'),
        ),
        migrations.AddField(
            model_name='todos',
            name='descend',
            field=models.TextField(null=True),
        ),
    ]
